<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as BaseVerifier;

class VerifyCsrfToken extends BaseVerifier
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    public function handle($request, Closure $next)
    {
        //使用csrf_token
//        return parent::handle($request, $next); // TODO: Change the autogenerated stub
        //禁用
        return $next($request);
    }
    /*protected $except = [
        //
    ];*/
}
